# Generated by Django 6.0.3 on 2026-03-04 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('answer', models.CharField(max_length=200)),
                ('answer_display', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('hint', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='puzzles/originals/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PuzzleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('image', models.ImageField(upload_to='puzzles/processed/')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='game.puzzle')),
            ],
            options={
                'ordering': ['level'],
                'unique_together': {('puzzle', 'level')},
            },
        ),
    ]
