# Generated by Django 6.0.3 on 2026-03-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='aliases',
            field=models.TextField(blank=True, help_text='Comma-separated alternative accepted answers, e.g. "queen, the queen". Lowercased automatically.'),
        ),
    ]
