# Generated by Django 6.0.3 on 2026-03-10 12:20

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_puzzle_aliases'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='stat_guess_distribution',
            field=models.JSONField(default=game.models._default_distribution),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='stat_plays',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='stat_wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
